#pragma once
#include "rndobj/BaseMaterial.h"

// size 0x204
/** "MetaMaterials serve as Material templates" */
class MetaMaterial : public BaseMaterial {
public:
    virtual ~MetaMaterial();
    OBJ_CLASSNAME(MetaMaterial);
    OBJ_SET_TYPE(MetaMaterial);
    virtual DataNode Handle(DataArray *, bool);
    virtual bool SyncProperty(DataNode &, DataArray *, int, PropOp);
    virtual void Save(BinStream &);
    virtual void Copy(const Hmx::Object *, Hmx::Object::CopyType);
    virtual void Load(BinStream &);

protected:
    MetaMaterial();
    /** "Approximate combinations of shaders generated by this MetaMat.
        More shaders means more memory is used." */
    int CalcApproxNumShaders();
    void SetEditAction(MatProp, MatPropEditAction);

    std::vector<MatPropEditAction> unk1f8;
};
