#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum _XPRIVILEGE_TYPE {
    XPRIVILEGE_MULTIPLAYER_SESSIONS = 0x00fe,
    XPRIVILEGE_COMMUNICATIONS = 0x00fc,
    XPRIVILEGE_COMMUNICATIONS_FRIENDS_ONLY = 0x00fb,
    XPRIVILEGE_PROFILE_VIEWING = 0x00f9,
    XPRIVILEGE_PROFILE_VIEWING_FRIENDS_ONLY = 0x00f8,
    XPRIVILEGE_USER_CREATED_CONTENT = 0x00f7,
    XPRIVILEGE_USER_CREATED_CONTENT_FRIENDS_ONLY = 0x00f6,
    XPRIVILEGE_PURCHASE_CONTENT = 0x00f5,
    XPRIVILEGE_PRESENCE = 0x00f4,
    XPRIVILEGE_PRESENCE_FRIENDS_ONLY = 0x00f3,
    XPRIVILEGE_TRADE_CONTENT = 0x00ee,
    XPRIVILEGE_VIDEO_COMMUNICATIONS = 0x00eb,
    XPRIVILEGE_VIDEO_COMMUNICATIONS_FRIENDS_ONLY = 0x00ea,
    XPRIVILEGE_SOCIAL_NETWORK_SHARING = 0x00dc,
    XPRIVILEGE_CONTENT_AUTHOR = 0x00de,
    XPRIVILEGE_UNSAFE_PROGRAMMING = 0x00d4,
    XPRIVILEGE_SHARE_CONTENT_OUTSIDE_LIVE = 0x00d3,
    XPRIVILEGE_INTERNET_BROWSING = 0x00d9,
};

typedef _XPRIVILEGE_TYPE XPRIVILEGE_TYPE;

unsigned int XUserCheckPrivilege(unsigned int, XPRIVILEGE_TYPE, int *);

#ifdef __cplusplus
}
#endif
